import { Inter } from "next/font/google";
import { Header } from "./components/shared/Header";
import { Footer } from "./components/shared/Footer";
import { Hero } from "./components/home/Hero";
import { MainProducts } from "./components/home/MainProducts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Header />
        <Hero />
        <MainProducts />
        {children}
        <Footer />  
      </body>
      
    </html>
  );
}
